In [27]:
import pandas as pd

In [28]:
courses = pd.read_csv("courses.csv")
assessments = pd.read_csv("assessments.csv")
studentAssessment = pd.read_csv("studentAssessment.csv")
studentInfo = pd.read_csv("studentInfo.csv")
studentRegistration = pd.read_csv("studentRegistration.csv")
studentVle = pd.read_csv("studentVle.csv")
vle = pd.read_csv("vle.csv")

In [29]:
datasets = {
    "courses": courses,
    "assessments": assessments,
    "studentAssessment": studentAssessment,
    "studentInfo": studentInfo,
    "studentRegistration": studentRegistration,
    "studentVle": studentVle,
    "vle": vle
}

for name, df in datasets.items():
    print(f"{name}: {df.shape}")

courses: (22, 3)
assessments: (206, 6)
studentAssessment: (173912, 5)
studentInfo: (32593, 12)
studentRegistration: (32593, 5)
studentVle: (10655280, 6)
vle: (6364, 6)

In [30]:
courses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   code_module                 22 non-null     object
 1   code_presentation           22 non-null     object
 2   module_presentation_length  22 non-null     int64
dtypes: int64(1), object(2)
memory usage: 660.0+ bytes

In [31]:
assessments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   code_module        206 non-null    object
 1   code_presentation  206 non-null    object
 2   id_assessment      206 non-null    int64
 3   assessment_type    206 non-null    object
 4   date               195 non-null    float64
 5   weight             206 non-null    float64
dtypes: float64(2), int64(1), object(3)
memory usage: 9.8+ KB

In [32]:
studentAssessment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173912 entries, 0 to 173911
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id_assessment   173912 non-null  int64
 1   id_student      173912 non-null  int64
 2   date_submitted  173912 non-null  int64
 3   is_banked       173912 non-null  int64
 4   score           173739 non-null  float64
dtypes: float64(1), int64(4)
memory usage: 6.6 MB

In [33]:
studentInfo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   code_module           32593 non-null  object
 1   code_presentation     32593 non-null  object
 2   id_student            32593 non-null  int64
 3   gender                32593 non-null  object
 4   region                32593 non-null  object
 5   highest_education     32593 non-null  object
 6   imd_band              31482 non-null  object
 7   age_band              32593 non-null  object
 8   num_of_prev_attempts  32593 non-null  int64
 9   studied_credits       32593 non-null  int64
 10  disability            32593 non-null  object
 11  final_result          32593 non-null  object
dtypes: int64(3), object(9)
memory usage: 3.0+ MB

In [34]:
studentRegistration.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   code_module          32593 non-null  object
 1   code_presentation    32593 non-null  object
 2   id_student           32593 non-null  int64
 3   date_registration    32548 non-null  float64
 4   date_unregistration  10072 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 1.2+ MB

In [35]:
studentVle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10655280 entries, 0 to 10655279
Data columns (total 6 columns):
 #   Column             Dtype
---  ------             -----
 0   code_module        object
 1   code_presentation  object
 2   id_student         int64
 3   id_site            int64
 4   date               int64
 5   sum_click          int64
dtypes: int64(4), object(2)
memory usage: 487.8+ MB

In [36]:
vle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6364 entries, 0 to 6363
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_site            6364 non-null   int64
 1   code_module        6364 non-null   object
 2   code_presentation  6364 non-null   object
 3   activity_type      6364 non-null   object
 4   week_from          1121 non-null   float64
 5   week_to            1121 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 298.4+ KB

In [37]:
vle.head()

   id_site code_module code_presentation activity_type  week_from  week_to
0   546943         AAA             2013J      resource        NaN      NaN
1   546712         AAA             2013J     oucontent        NaN      NaN
2   546998         AAA             2013J      resource        NaN      NaN
3   546888         AAA             2013J           url        NaN      NaN
4   547035         AAA             2013J      resource        NaN      NaN

In [38]:
vle['activity_type'].unique()

array(['resource', 'oucontent', 'url', 'homepage', 'subpage', 'glossary',
       'forumng', 'oucollaborate', 'dataplus', 'quiz', 'ouelluminate',
       'sharedsubpage', 'questionnaire', 'page', 'externalquiz', 'ouwiki',
       'dualpane', 'repeatactivity', 'folder', 'htmlactivity'],
      dtype=object)

In [39]:
for name, df in datasets.items():
    print("="*60)
    print(name)
    print(df.isnull().sum())

============================================================
courses
code_module                   0
code_presentation             0
module_presentation_length    0
dtype: int64
============================================================
assessments
code_module           0
code_presentation     0
id_assessment         0
assessment_type       0
date                 11
weight                0
dtype: int64
============================================================
studentAssessment
id_assessment       0
id_student          0
date_submitted      0
is_banked           0
score             173
dtype: int64
============================================================
studentInfo
code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                1111
age_band                   0
num_of_prev_attempts       0
studied_credits            0
disability                 0
final_result               0
dtype: int64
============================================================
studentRegistration
code_module                0
code_presentation          0
id_student                 0
date_registration         45
date_unregistration    22521
dtype: int64
============================================================
studentVle
code_module          0
code_presentation    0
id_student           0
id_site              0
date                 0
sum_click            0
dtype: int64
============================================================
vle
id_site                 0
code_module             0
code_presentation       0
activity_type           0
week_from            5243
week_to              5243
dtype: int64

In [40]:
for name, df in datasets.items():
    print(name)
    print(df.duplicated().sum())

courses
0
assessments
0
studentAssessment
0
studentInfo
0
studentRegistration
0
studentVle
787170
vle
0

In [44]:
studentVle['id_student'].unique()

array([ 28400,  30268,  31604, ..., 676034, 121182, 650630],
      shape=(26074,))

In [48]:
studentVle.shape

(10655280, 6)

In [49]:
studentVle.head()

  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1

### Initial Data Profiling Observations

• Successfully loaded all seven OULAD datasets.

• Largest dataset:
studentVle

• Smallest dataset:
courses

• Missing values observed in studentRegistration and studentAssessment.

• studentVle contains repeated student-resource-day records.

• Most ID columns are stored correctly as integers.

• Categorical columns are stored as objects.

## Data Quality Issues

1. Missing values present in selected datasets.

2. studentVle contains repeated records for the same student and learning resource.

3. Need to validate duplicate records before removal.

4. Need to verify relationships between datasets before merging.

In [50]:
studentVle.duplicated().sum()

np.int64(787170)

In [51]:
studentVle[
    (studentVle["id_student"] == 28400) &
    (studentVle["id_site"] == 546652) &
    (studentVle["date"] == -10)
]

  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
5         AAA             2013J       28400   546652   -10          8

In [54]:
studentVle_clean = (
    studentVle
    .groupby(
        [
            "code_module",
            "code_presentation",
            "id_student",
            "id_site",
            "date"
        ],
        as_index=False
    )
    .agg({"sum_click": "sum"})
)

In [56]:
studentVle_clean.duplicated().sum()

np.int64(0)

In [66]:
studentVle.head(60)

   code_module code_presentation  id_student  id_site  date  sum_click
0          AAA             2013J       28400   546652   -10          4
1          AAA             2013J       28400   546652   -10          1
2          AAA             2013J       28400   546652   -10          1
3          AAA             2013J       28400   546614   -10         11
4          AAA             2013J       28400   546714   -10          1
5          AAA             2013J       28400   546652   -10          8
6          AAA             2013J       28400   546876   -10          2
7          AAA             2013J       28400   546688   -10         15
8          AAA             2013J       28400   546662   -10         17
9          AAA             2013J       28400   546890   -10          1
10         AAA             2013J       28400   547011   -10          1
11         AAA             2013J       28400   547013   -10          1
12         AAA             2013J       28400   546871   -10          3
13         AAA             2013J       28400   546879   -10          4
14         AAA             2013J       30268   546652   -10          3
15         AAA             2013J       30268   546662   -10          2
16         AAA             2013J       30268   546614   -10          3
17         AAA             2013J       30268   546652   -10          2
18         AAA             2013J       31604   546672   -10          1
19         AAA             2013J       31604   547013   -10          5
20         AAA             2013J       31604   546871   -10          3
21         AAA             2013J       31604   546614   -10         11
22         AAA             2013J       31604   546660   -10          1
23         AAA             2013J       31604   546662   -10         19
24         AAA             2013J       31604   546879   -10          9
25         AAA             2013J       31604   546667   -10          4
26         AAA             2013J       31604   546688   -10          7
27         AAA             2013J       32885   546681   -10          5
28         AAA             2013J       32885   547013   -10          1
29         AAA             2013J       32885   546652   -10          1
30         AAA             2013J       32885   546614   -10         13
31         AAA             2013J       32885   546652   -10          3
32         AAA             2013J       32885   546662   -10         22
33         AAA             2013J       32885   546871   -10          1
34         AAA             2013J       32885   546660   -10          2
35         AAA             2013J       32885   546670   -10          1
36         AAA             2013J       32885   546719   -10          5
37         AAA             2013J       32885   546732   -10          5
38         AAA             2013J       32885   546668   -10          1
39         AAA             2013J       32885   546672   -10          1
40         AAA             2013J       32885   546667   -10          3
41         AAA             2013J       32885   546671   -10          1
42         AAA             2013J       32885   546879   -10          5
43         AAA             2013J       32885   546652   -10          4
44         AAA             2013J       32885   546731   -10          4
45         AAA             2013J       38053   546879   -10          7
46         AAA             2013J       38053   546986   -10          2
47         AAA             2013J       38053   546652   -10          5
48         AAA             2013J       38053   546681   -10          2
49         AAA             2013J       38053   546614   -10         13
50         AAA             2013J       38053   546669   -10          5
51         AAA             2013J       38053   546688   -10          2
52         AAA             2013J       38053   546700   -10          2
53         AAA             2013J       38053   546714   -10          2
54         AAA             2013J       38053   546719   -10          5
55         AAA             2013J       38053   546652   -10         11
56         AAA             2013J       38053   546662   -10         17
57         AAA             2013J       38053   546871   -10          1
58         AAA             2013J       38053   547013   -10          1
59         AAA             2013J       45462   546662   -10          1

In [67]:
studentVle=studentVle_clean

In [68]:
studentVle

        code_module code_presentation  id_student  id_site  date  sum_click
0               AAA             2013J       11391   546614    -5          7
1               AAA             2013J       11391   546614     0         10
2               AAA             2013J       11391   546614     1          9
3               AAA             2013J       11391   546614     2          3
4               AAA             2013J       11391   546614     6          1
...             ...               ...         ...      ...   ...        ...
8459315         GGG             2014J     2684003   897151    52          1
8459316         GGG             2014J     2684003   897151   100          1
8459317         GGG             2014J     2684003   897151   143          1
8459318         GGG             2014J     2684003   897151   156          1
8459319         GGG             2014J     2684003   897152     9          1

[8459320 rows x 6 columns]

In [69]:
studentInfo.nunique()

code_module                 7
code_presentation           4
id_student              28785
gender                      2
region                     13
highest_education           5
imd_band                   10
age_band                    3
num_of_prev_attempts        7
studied_credits            61
disability                  2
final_result                4
dtype: int64

In [74]:
studentInfo['disability'].value_counts()

disability
N    29429
Y     3164
Name: count, dtype: int64